DROP TABLE users CASCADE;
DROP TABLE forums CASCADE;
DROP TABLE threads CASCADE;
DROP TABLE status CASCADE;
DROP TABLE posts CASCADE;
DROP TABLE votes CASCADE;

DROP FUNCTION count_inserted_rows() CASCADE ;