ALTER TABLE posts
  SET ( AUTOVACUUM_VACUUM_THRESHOLD = 0),
  SET ( AUTOVACUUM_VACUUM_SCALE_FACTOR = 0.0),
  SET ( AUTOVACUUM_FREEZE_MIN_AGE = 0),
  SET ( AUTOVACUUM_FREEZE_MAX_AGE = 100000),
  SET (AUTOVACUUM_FREEZE_TABLE_AGE = 0);

ALTER TABLE votes
  SET ( AUTOVACUUM_VACUUM_THRESHOLD = 0),
  SET ( AUTOVACUUM_VACUUM_SCALE_FACTOR = 0.0),
  SET ( AUTOVACUUM_FREEZE_MIN_AGE = 0),
  SET ( AUTOVACUUM_FREEZE_MAX_AGE = 100000),
  SET (AUTOVACUUM_FREEZE_TABLE_AGE = 0);

ALTER TABLE threads
  SET ( AUTOVACUUM_VACUUM_THRESHOLD = 0),
  SET ( AUTOVACUUM_VACUUM_SCALE_FACTOR = 0.0),
  SET ( AUTOVACUUM_FREEZE_MIN_AGE = 0),
  SET ( AUTOVACUUM_FREEZE_MAX_AGE = 100000),
  SET (AUTOVACUUM_FREEZE_TABLE_AGE = 0);

ALTER TABLE users
  SET ( AUTOVACUUM_VACUUM_THRESHOLD = 0),
  SET ( AUTOVACUUM_VACUUM_SCALE_FACTOR = 0.0),
  SET ( AUTOVACUUM_FREEZE_MIN_AGE = 0),
  SET ( AUTOVACUUM_FREEZE_MAX_AGE = 100000),
  SET (AUTOVACUUM_FREEZE_TABLE_AGE = 0);